START TRANSACTION;

SET @admin_id := (
    SELECT id
    FROM users
    WHERE role_id IN (1, 2)
    ORDER BY role_id ASC, id ASC
    LIMIT 1
);

-- Safe to rerun: only replaces the package rows defined in this file.
DELETE b
FROM bookings b
JOIN tours t ON t.id = b.tour_id
WHERE t.title IN (
    'Everest Panorama Trek',
    'Annapurna Sanctuary Trek',
    'Kathmandu Heritage Walk',
    'Bhaktapur Newari Heritage Day',
    'Lumbini Buddhist Circuit',
    'Janakpur Mithila Culture Tour',
    'Pokhara Paragliding Escape',
    'Trishuli Rafting Adventure',
    'Pokhara Yoga and Lakeside Retreat',
    'Himalayan Ayurveda Retreat',
    'Chitwan Family Wildlife Safari',
    'Pokhara Family Lakeside Holiday',
    'Everest Helicopter Breakfast',
    'Mustang Luxury Jeep Escape',
    'Mustang Landscape Photography',
    'Rara Lake Photography Trek',
    'Nagarkot Sunrise Weekend',
    'Bandipur Weekend Heritage Escape',
    'Kathmandu Budget Heritage Break',
    'Annapurna Budget Poon Hill Trek'
);

DELETE FROM tours
WHERE title IN (
    'Everest Panorama Trek',
    'Annapurna Sanctuary Trek',
    'Kathmandu Heritage Walk',
    'Bhaktapur Newari Heritage Day',
    'Lumbini Buddhist Circuit',
    'Janakpur Mithila Culture Tour',
    'Pokhara Paragliding Escape',
    'Trishuli Rafting Adventure',
    'Pokhara Yoga and Lakeside Retreat',
    'Himalayan Ayurveda Retreat',
    'Chitwan Family Wildlife Safari',
    'Pokhara Family Lakeside Holiday',
    'Everest Helicopter Breakfast',
    'Mustang Luxury Jeep Escape',
    'Mustang Landscape Photography',
    'Rara Lake Photography Trek',
    'Nagarkot Sunrise Weekend',
    'Bandipur Weekend Heritage Escape',
    'Kathmandu Budget Heritage Break',
    'Annapurna Budget Poon Hill Trek'
);

INSERT INTO tours (
    title, location, price, duration, description, category, difficulty, max_group,
    highlights, image, best_season, altitude_max, permit_requirements, itinerary,
    inclusions, exclusions, is_featured, created_by
) VALUES
('Everest Panorama Trek', 'Everest', 88500.00, '7 Days',
'A shorter Everest region trek for travelers who want Sherpa culture, Namche Bazaar, Tengboche Monastery, and close Himalayan views without going all the way to base camp.',
'trekking', 'Moderate', 12,
'Lukla mountain flight\nNamche Bazaar\nEverest View Hotel viewpoint\nTengboche Monastery\nAma Dablam and Everest views\nSherpa village experience',
'assets/images/Everest/photo-1545918458-8394c4e4b21f.jpg', 'Spring, Autumn', 3860, 'Sagarmatha National Park Permit, Khumbu Pasang Lhamu Rural Municipality Permit',
'Day 1: Fly Kathmandu to Lukla, trek to Phakding\nDay 2: Trek to Namche Bazaar\nDay 3: Acclimatization hike to Everest View Hotel\nDay 4: Trek to Tengboche\nDay 5: Trek back to Namche\nDay 6: Trek to Lukla\nDay 7: Fly back to Kathmandu',
'Domestic flights\nTeahouse accommodation during trek\nLicensed guide\nPorter support\nPermits\nBasic first aid kit\nGovernment taxes',
'International flights\nNepal visa\nTravel insurance\nMeals in Kathmandu\nDrinks and snacks\nPersonal trekking gear\nTips',
1, @admin_id),

('Annapurna Sanctuary Trek', 'Annapurna', 98000.00, '10 Days',
'A classic journey into the Annapurna amphitheater through Gurung villages, rhododendron forests, Machhapuchhre Base Camp, and Annapurna Base Camp.',
'trekking', 'Moderate', 14,
'Ghorepani and Poon Hill\nChhomrong village\nMachhapuchhre Base Camp\nAnnapurna Base Camp\nJhinu hot springs\nAnnapurna South and Hiunchuli views',
'assets/images/Annapurna/pexels-photo-28293823.jpeg', 'Spring, Autumn', 4130, 'ACAP Permit, TIMS Card',
'Day 1: Drive Pokhara to Nayapul, trek to Tikhedhunga\nDay 2: Trek to Ghorepani\nDay 3: Poon Hill sunrise, trek to Tadapani\nDay 4: Trek to Chhomrong\nDay 5: Trek to Bamboo\nDay 6: Trek to Deurali\nDay 7: Trek to Annapurna Base Camp\nDay 8: Descend to Bamboo\nDay 9: Trek to Jhinu Danda\nDay 10: Drive back to Pokhara',
'Pokhara transfers\nTeahouse accommodation\nGuide and porter\nACAP and TIMS permits\nBreakfast, lunch, and dinner during trek\nGovernment taxes',
'Kathmandu-Pokhara transport\nTravel insurance\nPersonal gear\nHot shower and charging fees\nDrinks\nTips',
1, @admin_id),

('Kathmandu Heritage Walk', 'Kathmandu', 18500.00, '2 Days',
'A slow cultural walk through Kathmandu Durbar Square, Swayambhunath, Boudhanath, and Patan with stories of Newari art, courtyards, temples, and living heritage.',
'culture', 'Easy', 18,
'Kathmandu Durbar Square\nSwayambhunath Stupa\nBoudhanath Stupa\nPatan Durbar Square\nTraditional courtyards\nLocal tea stop',
'assets/images/kathmandu/meghraj-neupane-YtEzq-hnv5k-unsplash.jpg', 'Year-round', 1400, 'UNESCO monument entry tickets',
'Day 1: Kathmandu Durbar Square, Swayambhunath, and old market lanes\nDay 2: Boudhanath, Patan Durbar Square, artisan lanes, and departure',
'Licensed cultural guide\nPrivate city transport\nMonument entry fees\nTea tasting\nGovernment taxes',
'Hotel accommodation\nMeals unless specified\nPersonal shopping\nTips',
1, @admin_id),

('Bhaktapur Newari Heritage Day', 'Kathmandu', 14500.00, '1 Day',
'A one-day heritage experience in Bhaktapur focused on palace squares, pottery lanes, wood carving, local food, and Newari living culture.',
'culture', 'Easy', 16,
'Bhaktapur Durbar Square\nNyatapola Temple\nPottery Square\nPeacock Window\nNewari lunch tasting\nTraditional craft lanes',
'assets/images/kathmandu/f44d8c72a178b08a1712a1f379e2f155.jpg', 'Year-round', 1401, 'Bhaktapur entry ticket',
'Morning drive to Bhaktapur\nGuided walk through Durbar Square and Taumadhi\nPottery Square visit\nNewari lunch\nWood carving and local market walk\nReturn to Kathmandu',
'Private vehicle\nLicensed guide\nBhaktapur entry ticket\nNewari lunch tasting\nGovernment taxes',
'Extra meals\nPersonal purchases\nTips\nTravel insurance',
0, @admin_id),

('Lumbini Buddhist Circuit', 'Lumbini', 36500.00, '3 Days',
'A peaceful cultural journey through the birthplace of Buddha, monasteries, Maya Devi Temple, Ashoka Pillar, and surrounding Buddhist heritage sites.',
'culture', 'Easy', 18,
'Maya Devi Temple\nAshoka Pillar\nWorld Peace Pagoda\nInternational monasteries\nTilaurakot visit\nBuddhist heritage interpretation',
'assets/images/Lumbini/pexels-photo-6327865.jpeg', 'October to March', 150, 'Lumbini development area entry tickets',
'Day 1: Arrival in Lumbini and monastery zone walk\nDay 2: Maya Devi Temple, Ashoka Pillar, World Peace Pagoda, and Tilaurakot\nDay 3: Morning meditation time and departure',
'Hotel accommodation with breakfast\nPrivate transport\nLicensed guide\nEntry tickets\nGovernment taxes',
'Flights or long-distance bus unless requested\nLunch and dinner\nPersonal expenses\nTips',
1, @admin_id),

('Janakpur Mithila Culture Tour', 'Janakpur', 29500.00, '3 Days',
'A colorful cultural tour of Janakpur focused on Janaki Mandir, Mithila art, local markets, ponds, rituals, and Maithil hospitality.',
'culture', 'Easy', 16,
'Janaki Mandir\nMithila art workshop\nSacred ponds\nLocal market walk\nMaithil food tasting\nRam-Janaki heritage stories',
'https://commons.wikimedia.org/wiki/Special:Redirect/file/Janaki%20Temple%20Janakpur-Janakpur030315%20MG%2036680059.jpg?width=1200', 'October to March', 74, 'Local monument tickets where applicable',
'Day 1: Travel to Janakpur and evening market walk\nDay 2: Janaki Mandir, Mithila art workshop, sacred ponds, and local food\nDay 3: Morning temple visit and return',
'Local guide\nPrivate transport in Janakpur\nTwo nights hotel with breakfast\nWorkshop fee\nGovernment taxes',
'Kathmandu-Janakpur flights unless requested\nLunch and dinner\nPersonal shopping\nTips',
0, @admin_id),

('Pokhara Paragliding Escape', 'Pokhara', 32000.00, '3 Days',
'An adventure break in Pokhara with tandem paragliding, Phewa Lake time, Sarangkot sunrise, and relaxed lakeside evenings.',
'adventure', 'Easy', 12,
'Tandem paragliding\nSarangkot sunrise\nPhewa Lake boating\nWorld Peace Pagoda\nLakeside evening\nAnnapurna range views',
'assets/images/Pokhara/pexels-photo-14892590.jpeg', 'September to May', 1600, 'No trekking permit required',
'Day 1: Arrive Pokhara and lakeside orientation\nDay 2: Sarangkot sunrise, tandem paragliding, and Phewa Lake boating\nDay 3: Peace Pagoda visit and departure',
'Two nights hotel with breakfast\nParagliding session\nBoating fee\nLocal transfers\nGuide assistance\nGovernment taxes',
'Kathmandu-Pokhara transport\nMeals not listed\nWeather delay costs\nTravel insurance\nTips',
0, @admin_id),

('Trishuli Rafting Adventure', 'Trishuli River', 18000.00, '2 Days',
'A beginner-friendly rafting trip on the Trishuli River with riverside camping, safety briefing, rapids, and scenic highway access from Kathmandu or Pokhara.',
'adventure', 'Moderate', 20,
'White-water rafting\nRiverside camp\nSafety kayak support\nCampfire evening\nHighway access\nBeginner friendly rapids',
'https://media.himalayanriverfun.com/uploads/fullbanner/trishuli-river-rafting.webp', 'September to June', 600, 'No permit required for standard rafting section',
'Day 1: Drive to rafting put-in point, safety briefing, rafting, riverside camp\nDay 2: Morning rafting section, lunch, and drive onward',
'Rafting equipment\nCertified river guide\nRiverside camp\nMeals during rafting\nSafety briefing\nLocal transfers from meeting point',
'Kathmandu/Pokhara hotel pickup outside route\nPersonal insurance\nAlcoholic drinks\nTips',
0, @admin_id),

('Pokhara Yoga and Lakeside Retreat', 'Pokhara', 42000.00, '4 Days',
'A gentle wellness retreat with lakeside yoga, meditation, sound healing, easy nature walks, and nourishing vegetarian meals in Pokhara.',
'wellness', 'Easy', 12,
'Daily yoga sessions\nGuided meditation\nSound healing\nPhewa Lake walk\nVegetarian meals\nOptional massage session',
'assets/images/Pokhara/pexels-photo-29377640.jpeg', 'Year-round', 900, 'No permit required',
'Day 1: Arrival and evening meditation\nDay 2: Morning yoga, lake walk, and sound healing\nDay 3: Yoga, free time, optional massage, and sunset reflection\nDay 4: Closing practice and departure',
'Three nights retreat accommodation\nDaily breakfast and dinner\nYoga and meditation teacher\nSound healing session\nLocal support\nGovernment taxes',
'Transport to Pokhara\nLunch unless specified\nSpa treatments not listed\nPersonal expenses\nTips',
0, @admin_id),

('Himalayan Ayurveda Retreat', 'Kathmandu', 52000.00, '5 Days',
'A wellness-focused Kathmandu Valley retreat combining Ayurveda consultation, gentle yoga, herbal therapy, cultural visits, and quiet recovery time.',
'wellness', 'Easy', 10,
'Ayurveda consultation\nGentle yoga\nHerbal steam or massage session\nHealthy meals\nKathmandu valley nature walk\nCultural temple visit',
'assets/images/guest_experience.jpg', 'Year-round', 1600, 'No trekking permit required',
'Day 1: Arrival and wellness consultation\nDay 2: Yoga, Ayurveda treatment, and rest\nDay 3: Nature walk and herbal therapy\nDay 4: Cultural visit and guided meditation\nDay 5: Final consultation and departure',
'Four nights accommodation\nBreakfast and selected wellness meals\nAyurveda consultation\nTwo therapy sessions\nYoga instructor\nLocal transport for included visits',
'International flights\nFull medical treatment\nExtra spa services\nPersonal expenses\nTips',
0, @admin_id),

('Chitwan Family Wildlife Safari', 'Chitwan', 46500.00, '3 Days',
'A family-friendly wildlife package in Chitwan with jeep safari, canoe ride, Tharu culture, elephant breeding center, and naturalist-guided activities.',
'family', 'Easy', 18,
'Jeep safari\nCanoe ride\nTharu cultural dance\nElephant breeding center\nBird watching\nKid-friendly naturalist guide',
'assets/images/Chitwan/pexels-photo-13228528.jpeg', 'October to March', 150, 'Chitwan National Park Entry Permit',
'Day 1: Arrive Chitwan and Tharu cultural program\nDay 2: Canoe ride, jungle walk, jeep safari, and elephant breeding center\nDay 3: Bird watching and departure',
'Two nights jungle lodge\nFull board meals\nNational park permits\nNaturalist guide\nSafari activities\nGovernment taxes',
'Kathmandu-Chitwan transport unless requested\nDrinks\nPersonal expenses\nTips',
1, @admin_id),

('Pokhara Family Lakeside Holiday', 'Pokhara', 38500.00, '4 Days',
'A relaxed family holiday in Pokhara with easy sightseeing, boating, caves, sunrise viewpoints, and flexible pacing for children and elders.',
'family', 'Easy', 16,
'Phewa Lake boating\nDavis Falls\nGupteshwor Cave\nSarangkot sunrise\nPeace Pagoda\nFamily-friendly pacing',
'assets/images/Pokhara/pexels-photo-33208927.jpeg', 'Year-round', 1600, 'No permit required',
'Day 1: Arrive Pokhara and lakeside walk\nDay 2: Sarangkot sunrise, caves, Davis Falls, and boating\nDay 3: Peace Pagoda and free family time\nDay 4: Departure',
'Three nights hotel with breakfast\nPrivate sightseeing vehicle\nBoating fee\nGuide assistance\nEntry tickets\nGovernment taxes',
'Kathmandu-Pokhara transport\nLunch and dinner\nOptional activities\nPersonal expenses\nTips',
0, @admin_id),

('Everest Helicopter Breakfast', 'Everest', 285000.00, '1 Day',
'A premium helicopter experience to the Everest region with aerial views, landing near high Himalayan viewpoints, and breakfast at Everest View Hotel when weather permits.',
'luxury', 'Easy', 5,
'Private/shared helicopter flight\nEverest aerial views\nEverest View Hotel breakfast\nKala Patthar or viewpoint landing when permitted\nLuxury transfer coordination\nFast Himalayan experience',
'https://images.unsplash.com/photo-1575819719798-83d97dd6949c?auto=format&fit=crop&w=1200&q=80', 'March to May, September to November', 3880, 'Sagarmatha National Park and local landing permissions',
'Early morning hotel pickup\nHelicopter flight to Everest region\nViewpoint landing subject to weather and aviation rules\nBreakfast stop\nReturn flight to Kathmandu\nHotel drop-off',
'Helicopter seat\nAirport transfers\nBreakfast stop where available\nRequired landing/park fees\nFlight coordination\nGovernment taxes',
'Weather delays\nPersonal insurance\nExtra meals\nPersonal expenses\nTips',
1, @admin_id),

('Mustang Luxury Jeep Escape', 'Mustang', 168000.00, '6 Days',
'A comfort-focused overland journey through Lower Mustang with Jomsom, Kagbeni, Muktinath, Marpha, dramatic desert landscapes, and selected boutique stays.',
'luxury', 'Easy', 8,
'Private jeep journey\nKagbeni village\nMuktinath Temple\nMarpha apple village\nNilgiri and Dhaulagiri views\nComfort-focused pacing',
'assets/images/Mustang/pexels-photo-29053940.jpeg', 'March to November', 3800, 'ACAP Permit',
'Day 1: Fly or drive to Pokhara\nDay 2: Drive/fly to Jomsom, visit Marpha\nDay 3: Kagbeni and Muktinath excursion\nDay 4: Explore Lower Mustang villages\nDay 5: Return to Pokhara\nDay 6: Return to Kathmandu',
'Private jeep in Mustang\nSelected hotels with breakfast\nGuide/driver\nACAP permit\nAirport/road coordination\nGovernment taxes',
'Flights unless selected\nLunch and dinner\nPersonal expenses\nTravel insurance\nTips',
0, @admin_id),

('Mustang Landscape Photography', 'Mustang', 128000.00, '7 Days',
'A photography-focused Mustang journey timed for desert light, old villages, monasteries, ridgelines, and Himalayan textures with flexible golden-hour stops.',
'photography', 'Moderate', 8,
'Golden-hour desert landscapes\nKagbeni alleys\nMuktinath region\nMarpha village\nMonastery details\nGuided photo stops',
'assets/images/Mustang/pexels-photo-34714289.jpeg', 'March to November', 3800, 'ACAP Permit',
'Day 1: Travel to Pokhara\nDay 2: Travel to Jomsom and scout locations\nDay 3: Kagbeni sunrise and village photography\nDay 4: Muktinath and desert ridges\nDay 5: Marpha and apple orchards\nDay 6: Return to Pokhara\nDay 7: Buffer or departure',
'Local transport\nGuide/driver familiar with photo stops\nAccommodation with breakfast\nACAP permit\nFlexible sunrise/sunset schedule\nGovernment taxes',
'Camera equipment\nFlights unless selected\nMeals not listed\nTravel insurance\nTips',
0, @admin_id),

('Rara Lake Photography Trek', 'Rara Lake', 152000.00, '8 Days',
'A remote photography journey to Rara Lake with forest trails, blue alpine water, reflections, local villages, and quiet sunrise/sunset shooting windows.',
'photography', 'Moderate', 10,
'Rara Lake sunrise\nReflection photography\nForest trails\nRemote villages\nRara National Park\nLow-crowd destination',
'assets/images/Rara/pexels-photo-13319002.jpeg', 'April to June, September to November', 2990, 'Rara National Park Permit',
'Day 1: Fly Kathmandu to Nepalgunj\nDay 2: Fly to Talcha and walk to Rara\nDay 3: Sunrise and lakeside photography\nDay 4: Forest and village photo walk\nDay 5: Ridge viewpoint shoot\nDay 6: Return toward Talcha\nDay 7: Fly to Nepalgunj\nDay 8: Fly to Kathmandu',
'Domestic flights\nBasic lodge/camping support\nGuide\nNational park permit\nMeals during remote section\nGovernment taxes',
'Flight delay costs\nCamera gear\nInsurance\nExtra hotel nights\nPersonal expenses\nTips',
0, @admin_id),

('Nagarkot Sunrise Weekend', 'Kathmandu', 16500.00, '2 Days',
'A quick Kathmandu Valley weekend escape with sunset, sunrise over Himalayan ranges, easy village walks, and a calm overnight stay outside the city.',
'weekend', 'Easy', 18,
'Nagarkot sunset\nHimalayan sunrise\nEasy village walk\nBhaktapur optional stop\nShort drive from Kathmandu\nRelaxed overnight stay',
'https://commons.wikimedia.org/wiki/Special:Redirect/file/Before%20sunrise%20over%20the%20Himalayas%20-%20Flickr%20-%20Nasir%20Khan%20Saikat.jpg?width=1200', 'October to April', 2175, 'No trekking permit required',
'Day 1: Drive to Nagarkot with optional Bhaktapur stop, sunset viewpoint\nDay 2: Sunrise viewing, village walk, return to Kathmandu',
'Private transport\nOne night hotel with breakfast\nGuide assistance\nBhaktapur stop coordination if selected\nGovernment taxes',
'Lunch and dinner\nBhaktapur entry ticket if selected\nPersonal expenses\nTips',
0, @admin_id),

('Bandipur Weekend Heritage Escape', 'Bandipur', 22500.00, '2 Days',
'A charming weekend in Bandipur with preserved Newari architecture, hilltop views, village lanes, Siddha Cave option, and slow heritage atmosphere.',
'weekend', 'Easy', 14,
'Bandipur bazaar\nNewari architecture\nHimalayan viewpoint\nSiddha Cave option\nVillage walk\nQuiet heritage stay',
'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bandipur%20%E2%80%93%20Balabazar%20-%2001.jpg?width=1200', 'Year-round', 1030, 'No trekking permit required',
'Day 1: Drive to Bandipur, heritage bazaar walk, sunset viewpoint\nDay 2: Village walk or Siddha Cave option, return journey',
'One night hotel with breakfast\nLocal guide\nPrivate transport from meeting point\nGovernment taxes',
'Meals not listed\nCave entry fees if selected\nPersonal expenses\nTips',
0, @admin_id),

('Kathmandu Budget Heritage Break', 'Kathmandu', 9500.00, '1 Day',
'A budget-friendly Kathmandu cultural day covering major heritage highlights with efficient routing, public/local-style transport options, and a licensed guide.',
'budget', 'Easy', 20,
'Kathmandu Durbar Square\nSwayambhunath\nBoudhanath\nLocal food stop\nBudget-friendly route\nLicensed guide',
'assets/images/kathmandu/Trishna_Shakya_kumari.jpg', 'Year-round', 1400, 'Monument entry tickets',
'Morning Kathmandu Durbar Square\nSwayambhunath viewpoint\nLocal lunch area\nBoudhanath evening walk\nTour ends in Kathmandu',
'Licensed guide\nRoute planning\nBasic local transport support\nGovernment taxes',
'Monument tickets\nMeals\nPrivate vehicle\nPersonal expenses\nTips',
0, @admin_id),

('Annapurna Budget Poon Hill Trek', 'Annapurna', 54500.00, '5 Days',
'A value-focused short trek to Poon Hill for sunrise views of Annapurna and Dhaulagiri, using teahouses and efficient routing from Pokhara.',
'budget', 'Moderate', 14,
'Poon Hill sunrise\nGhorepani village\nRhododendron forest\nAnnapurna and Dhaulagiri views\nShort trek format\nBudget teahouses',
'assets/images/Annapurna/pexels-photo-2902939.jpeg', 'Spring, Autumn', 3210, 'ACAP Permit, TIMS Card',
'Day 1: Pokhara to Nayapul, trek to Tikhedhunga\nDay 2: Trek to Ghorepani\nDay 3: Poon Hill sunrise, trek to Tadapani\nDay 4: Trek to Ghandruk\nDay 5: Trek out and drive to Pokhara',
'Pokhara trailhead transport\nTeahouse accommodation\nGuide\nACAP and TIMS permits\nBasic first aid\nGovernment taxes',
'Meals and drinks unless selected\nPorter service unless requested\nPersonal gear\nInsurance\nTips',
0, @admin_id);

COMMIT;
